### ISSUE TITLE
Bastion has randomly stopped working in general chat but no-where else

### ISSUE THREAD

**Issue by redbart** [AlphaKretin/bastion-bot#31] opened 2018-05-18 17:59 UTC
Commands in general chat work, but looking up cards doesn't. I have uninstalled the bot recently, and I think that may be the problem. EDIT: I have figured out the problem but need some help, I am using your public bot and I kicked it and re-added it while a trivia game was happening, I guess this put the chat in a weird glitched "trivia state", not allowing me to look up cards. How do I get my chat out of this "trivia state"? Any help would be much appreciated! P.S. Also the .trivia command doesn't work, I have tried it, but all other commands do except looking up cards.

**Comment by AlphaKretin** [comment] 2018-05-19 01:00
I'm aware of issues with Trivia where it sometimes abruptly stops without clearing its data. This sounds like the same issue caused another way. To prevent cheating, you can't look up cards during a game, so that's why that doesn't work either. I'm not sure what causes it, but one of my first priorities when my personal situation improves and I can work on Bastion again will be to implement a command that should clear the junk trivia data and make things work again. Until then, it seems to resolve itself after some time, or when Bastion is restarted.

**Comment by redbart** [comment] 2018-05-19 06:32
Thanks, it appears to have resolved itself overnight and everything is working

**Comment by AlphaKretin** [comment] 2018-05-21 00:11
The above commit adds a new command to deal with this issue. When Trivia freezes, just use the `.tfix` command. I don't anticipate figuring out the cause of the freezes, so this is as fixed as it's going to get in the near future, so I'll close the issue now. Lemme know if you have any issues with `.tfix`.

**Closed by AlphaKretin** 2018-05-21 00:11 UTC
